### ISSUE TITLE
Raspberry pi support

### ISSUE THREAD

**Issue by michaelachrisco** [chrisvfritz/isabella#1]
Interesting project! I would love to see it supported on a platform such as the raspberry pi.

**Comment by michaelachrisco** [comment]
Ill give it a try on my system at home and report back. Might need to do a switch of `tts` to `espeak` gems in order to get it working.

**Comment by chrisvfritz** [comment]
I have her on a Raspbery Pi B+ running Raspbian, so the Pi is officially supported. :smiley: I just plugged in a USB mic, speakers, and a wireless dongle.

**Comment by michaelachrisco** [comment]
In that case I am closing this sucker ;) Nice job!
